POST http://localhost:3001/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVydXNlciIsImlkIjoiNjJmNmY3ZWFkMWQ4ZTY4OGFlZjdmNGVjIiwiaWF0IjoxNjYwMzU2MzU3fQ.ZFItppaHEgQzfVW3vhcdR9d-If0U7_MFUc7kF44y_Sw
Content-Type: application/json

{
    "title": "The key to the universe",
    "author": "Ade's momma",
    "url": "google.com",
    "likes": 9
}